# SPDX-FileCopyrightText: 2026 Institute for Common Good Technology
#
# SPDX-License-Identifier: CC-BY-NC-SA-4.0

---
roles:
  - name: robertdebock.bootstrap

collections:
  - name: community.postgresql
