# SPDX-FileCopyrightText: 2026 Institute for Common Good Technology
#
# SPDX-License-Identifier: CC-BY-NC-SA-4.0

---
- name: Install debconf-utils
  # required by ansible.builtin.debconf
  ansible.builtin.package:
    name: debconf-utils
    state: present

- name: Set user for IntelMQ API
  ansible.builtin.debconf:
    name: intelmq-api
    question: intelmq-api/user
    value: "{{ intelmq_api_username }}"
    vtype: string
- name: Set password for IntelMQ API
  ansible.builtin.debconf:
    name: intelmq-api
    question: intelmq-api/password
    value: "{{ intelmq_api_password }}"
    vtype: password
- name: Set password-repeat for IntelMQ API
  ansible.builtin.debconf:
    name: intelmq-api
    question: intelmq-api/password-repeat
    value: "{{ intelmq_api_password }}"
    vtype: password
