---
- name: Set webserver service name
  ansible.builtin.set_fact:
    webserver: apache2
- name: Set redis service name
  ansible.builtin.set_fact:
    redis: redis-server

- name: Get package facts
  ansible.builtin.package_facts:
    manager: "auto"
