# SPDX-FileCopyrightText: 2026 Institute for Common Good Technology
#
# SPDX-License-Identifier: CC-BY-NC-SA-4.0

---
- name: Set webserver service name
  ansible.builtin.set_fact:
    webserver: apache2
- name: Set redis service name
  ansible.builtin.set_fact:
    redis: redis-server

- name: Get package facts
  ansible.builtin.package_facts:
    manager: "auto"
  # when: not ansible_check_mode
