---
- name: check if /etc/aliases exists
  stat:
    path: /etc/aliases
  register: etc_aliases

- name: Redirect IntelMQ system mails
  lineinfile:
    path: /etc/aliases
    regexp: "^intelmq:"
    line: "intelmq: {{ redirect_mail }}"
  notify: newaliases
  when: etc_aliases.stat.exists
