---
- import_tasks: facts.yml
  tags:
  - packages
  - intelmq
- import_tasks: package.yml
  tags:
  - packages
  - intelmq
  when: "'intelmq-manager' not in ansible_facts.packages"
- import_tasks: mail.yml
  tags:
  - intelmq
  - mail
  when: redirect_mail|length

- import_tasks: runtime.yml
  tags:
  - intelmq
  - configuration
