---
- import_tasks: facts.yml
  tags:
  - packages
  - intelmq
- import_tasks: package.yml
  tags:
  - packages
  - intelmq
- import_tasks: mail.yml
  tags:
  - intelmq
  - mail
  when: redirect_mail|length
