# SPDX-FileCopyrightText: 2026 Institute for Common Good Technology
#
# SPDX-License-Identifier: CC-BY-NC-SA-4.0

---
- name: Import facts tasks
  ansible.builtin.import_tasks: facts.yml
  tags:
    - packages
    - intelmq
- name: Import package tasks
  ansible.builtin.import_tasks: package.yml
  tags:
    - packages
    - intelmq
- name: Import mail tasks
  ansible.builtin.import_tasks: mail.yml
  tags:
    - intelmq
    - mail
  when: redirect_mail

- name: Import runtime tasks
  ansible.builtin.import_tasks: runtime.yml
  tags:
    - intelmq
    - configuration

- name: Import certbund tasks
  ansible.builtin.import_tasks: certbund.yml
  tags:
    - intelmq
    - certbund

- name: Import check tasks
  ansible.builtin.import_tasks: check.yml
  tags:
    - intelmq

- name: Import database tasks
  ansible.builtin.import_tasks: database.yml
  tags:
    - intelmq
    - database

- name: Import mailgen tasks
  ansible.builtin.import_tasks: mailgen.yml
  tags:
    - intelmq
    - mailgen

- name: Import fody tasks
  ansible.builtin.import_tasks: fody.yml
  tags:
    - intelmq
    - fody

- name: Import monitoring tasks  # noqa: name[missing]
  ansible.builtin.import_tasks: 05-intelmq-monitoring.yaml
  environment: "{{ proxy_env }}"
  when: checkmk
  tags:
    - intelmq
    - checkmk
