---
- import_tasks: debian_pre.yml
  when: ansible_distribution == 'Debian' and 'intelmq-api' not in ansible_facts.packages

- name: APT key
  apt_key:
    url: "https://download.opensuse.org/repositories/home:sebix:intelmq/{{ ansible_distribution }}_{{ ansible_distribution_major_version }}/Release.key"
    state: present
- name: IntelMQ stable repository
  apt_repository:
    repo: "deb http://download.opensuse.org/repositories/home:/sebix:/intelmq/{{ ansible_distribution }}_{{ ansible_distribution_major_version }}/ /"
    state: present
- name: Install IntelMQ packages
  package:
    name: "{{ item }}"
  loop:
  - intelmq-manager
  - intelmq-api
  - intelmq

# services configuration
- name: Make sure redis is running
  service:
    state: started
    enabled: yes
    name: "{{ redis }}"
- name: Make sure webserver is running
  service:
    state: started
    enabled: yes
    name: "{{ webserver }}"
