---
- name: Read runtime.yaml
  slurp:
    path: /etc/intelmq/runtime.yaml
  register: intelmq_runtime_raw
  when: not intelmq_runtime_clean
- name: parse runtime.yaml
  set_fact:
    original_intelmq_runtime: "{{ intelmq_runtime_raw['content'] | b64decode | from_yaml }}"
  when: not intelmq_runtime_clean

- name: merge runtime
  set_fact:
    new_intelmq_runtime: "{{ original_intelmq_runtime | combine(intelmq_runtime, recursive=True) }}"
  when: not intelmq_runtime_clean
- name: create new runtime
  set_fact:
    new_intelmq_runtime: "{{ intelmq_runtime }}"
  when: intelmq_runtime_clean

- name: Make runtime.yaml backup
  copy:
    src: /etc/intelmq/runtime.yaml
    dest: /etc/intelmq/runtime.yaml.bak
    remote_src: yes
    mode: '0640'

- name: Write runtime.yaml
  copy:
    content: "{{ new_intelmq_runtime | to_nice_yaml(indent=2) }}"
    dest: /etc/intelmq/runtime.yaml
    mode: '0640'
