---
- name: Read runtime.yaml
  ansible.builtin.slurp:
    path: /etc/intelmq/runtime.yaml
  register: intelmq_runtime_raw
- name: parse runtime.yaml
  ansible.builtin.set_fact:
    original_intelmq_runtime: "{{ intelmq_runtime_raw['content'] | b64decode | from_yaml }}"

- name: merge runtime
  ansible.builtin.set_fact:
    new_intelmq_runtime: "{{ original_intelmq_runtime | combine(intelmq_runtime, recursive=True) }}"
  when: not intelmq_runtime_clean
- name: create new runtime
  ansible.builtin.set_fact:
    new_intelmq_runtime: "{{ intelmq_runtime }}"
  when: intelmq_runtime_clean

- name: Make runtime.yaml backup
  ansible.builtin.copy:
    src: /etc/intelmq/runtime.yaml
    dest: /etc/intelmq/runtime.yaml.bak
    remote_src: yes
    mode: '0640'
  when: "original_intelmq_runtime != new_intelmq_runtime"

- name: Write runtime.yaml
  ansible.builtin.copy:
    content: "{{ new_intelmq_runtime | to_nice_yaml(indent=2) }}"
    dest: /etc/intelmq/runtime.yaml
    mode: '0640'
  notify: intelmqctl reload
