# SPDX-FileCopyrightText: 2026 Institute for Common Good Technology
#
# SPDX-License-Identifier: CC-BY-NC-SA-4.0

---
- name: Run all
  hosts: all
  # vars:
  #   ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: sebix.intelmq
      vars:
        intelmq_api_username: intelmqadmin
        intelmq_api_password: intelmqadmin
        intelmq_runtime_clean: true
        intelmq_unstable_repository: true
      diff: true
