---
- name: Run all
  hosts: all
  vars:
#    ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: ansible-intelmq
      vars:
        intelmq_api_username: intelmqadmin
        intelmq_api_password: intelmqadmin
        intelmq_runtime_clean: yes
