---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: "ansible-intelmq-${image:-fedora}-${tag:-latest}${TOX_ENVNAME}"
    image: fedora:latest
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  log: true
  name: ansible
verifier:
  name: ansible
