---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: "ansible-intelmq-${image:-fedora}-${tag:-latest}${TOX_ENVNAME}"
    image: "${namespace:-sebix}/${image:-fedora}:${tag:-latest}"
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: yes
provisioner:
  log: true
  name: ansible
verifier:
  name: ansible
