# SPDX-FileCopyrightText: 2026 Institute for Common Good Technology
#
# SPDX-License-Identifier: CC-BY-NC-SA-4.0

---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: "ansible-intelmq-${image:-ubuntu}-${tag:-latest}${TOX_ENVNAME}"
    image: "robertdebock/${image:-ubuntu}:${tag:-latest}"
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  log: true
  name: ansible
verifier:
  name: ansible
