# SPDX-FileCopyrightText: 2026 Institute for Common Good Technology
#
# SPDX-License-Identifier: CC-BY-NC-SA-4.0

---
- name: Prepare
  hosts: all
  gather_facts: false
  become: true

  roles:
    - role: robertdebock.bootstrap

- name: Start PostgreSQL for molecule tests
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Install PostgreSQL
      ansible.builtin.package:
        name: postgresql
        state: present

    - name: Start PostgreSQL
      ansible.builtin.service:
        name: postgresql
        state: started
        enabled: true
