# SPDX-FileCopyrightText: 2022-2026 Institute for Common Good Technology
#
# SPDX-License-Identifier: CC-BY-NC-SA-4.0

# uses https://github.com/ansible/ansible-lint
---
name: Ansible Lint

on: [push, pull_request]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint@main
