---
name: Push to Ansible Galaxy

on:
  workflow_run:
    workflows: ["Run molecule"]
    branches: ["main"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: to Ansible Galaxy
        uses: robertdebock/galaxy-action@1.1.1
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
