# SPDX-FileCopyrightText: 2022-2026 Institute for Common Good Technology
#
# SPDX-License-Identifier: CC-BY-NC-SA-4.0

---
name: Run molecule

on: [push, pull_request]

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: "${{ github.repository }}"

      - name: Run molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_options: --base-config molecule/default/molecule.yml
          molecule_command: test
          molecule_working_dir: "${{ github.repository }}"
