# SPDX-FileCopyrightText: 2022,2026 Institute for Common Good Technology
#
# SPDX-License-Identifier: CC-BY-NC-SA-4.0

---
name: Run molecule

on: [push, pull_request]

jobs:
  molecule:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        image:
#          - image: "enterpriselinux"
#            tag: "latest"
          - image: "debian"
            tag: "bullseye"
#          - image: "debian"
#            tag: "bookworm"
#          - image: "fedora"
#            tag: "34"
#          - image: "fedora"
#            tag: "latest"
#          - image: "opensuse"
#            tag: "latest"
          - image: "ubuntu"
            tag: "latest"
    steps:
      - name: checkout the repository
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"

      - name: molecule
        uses: robertdebock/molecule-action@4.0.7
        with:
          image: ${{ matrix.distribution.image }}
          tag: ${{ matrix.distribution.tag }}
          options: parallel
