# SPDX-FileCopyrightText: 2022-2026 Institute for Common Good Technology
#
# SPDX-License-Identifier: CC-BY-NC-SA-4.0

---
name: Run molecule

on: [push, pull_request]

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
#          - image: "enterpriselinux"
#            tag: "latest"
#          - image: "debian"
#            tag: "bullseye"
#          - image: "debian"
#            tag: "bookworm"
#          - image: "fedora"
#            tag: "34"
#          - image: "fedora"
#            tag: "latest"
#          - image: "opensuse"
#            tag: "latest"
          - image: "ubuntu"
            tag: "24.04"
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: "${{ github.repository }}"

      - name: Run molecule
        uses: robertdebock/molecule-action@master
        with:
          image: ${{ matrix.image.image }}
          tag: ${{ matrix.image.tag }}
          options: parallel
