# SPDX-FileCopyrightText: 2022 Institute for Common Good Technology
#
# SPDX-License-Identifier: CC-BY-NC-SA-4.0

---
name: Yaml Lint
on:
  push:

jobs:
  yamllint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v6
      - name: yamllint
        uses: ibiqlik/action-yamllint@v3
